"""Rename orders table to order for naming consistency

Revision ID: b207841bd500
Revises: 75bbc2f1121a
Create Date: 2026-02-02 18:24:02.211525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b207841bd500'
down_revision: Union[str, Sequence[str], None] = '75bbc2f1121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint on order_product
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    
    # Rename the orders table to "order" (quote because it's a reserved word in PostgreSQL)
    op.execute('ALTER TABLE orders RENAME TO "order"')
    
    # Rename the sequence for the id column
    op.execute('ALTER SEQUENCE orders_id_seq RENAME TO order_id_seq')
    
    # Create the foreign key constraint pointing to the new "order" table
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint on order_product
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    
    # Rename the sequence back
    op.execute('ALTER SEQUENCE order_id_seq RENAME TO orders_id_seq')
    
    # Rename the "order" table back to orders
    op.execute('ALTER TABLE "order" RENAME TO orders')
    
    # Recreate the foreign key constraint pointing to orders table
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
